# Generated by Django 5.2 on 2025-04-14 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-reference_date'],
            },
        ),
        migrations.CreateModel(
            name='IndicesConstrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('incc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cub', models.DecimalField(decimal_places=2, max_digits=8)),
                ('variacao_mensal', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Índice da Construção',
                'verbose_name_plural': 'Índices da Construção',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('published_date', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_atualizacao', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Preço de Material',
                'verbose_name_plural': 'Preços de Materiais',
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('fonte', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='BulkQuoteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotes/', verbose_name='Arquivo')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Material')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Loja')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('url', models.URLField(verbose_name='Link do Produto')),
                ('store_contact', models.CharField(blank=True, max_length=255, verbose_name='Contato da Loja')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Região')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('material_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_intelligence.materialquote')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
